# Generated by Django 3.0.5 on 2020-12-06 06:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_Number', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(default='India', max_length=2)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
