# Generated by Django 3.0.5 on 2020-12-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donar',
            new_name='Donate',
        ),
    ]
