# Generated by Django 3.0.5 on 2020-12-06 07:20

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0002_auto_20201206_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_Number', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(default='India', max_length=2)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='Mobile_Number',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='password',
        ),
    ]
